PREFIX: '&b&lOneBlock '

block-to-change: 'DIAMOND_BLOCK' #When you create an island, it will turn all blocks with this type to OneBlock
autopickup: true
blacklisted-blocks-enabled: true #If this set to true, all the blocks listed here will be blocked and never spawned
blacklisted-blocks: #Text not ID
  - 'AIR'
  - 'COMMAND_BLOCK'
  - 'WOOD_DOOR'
  - 'BED'
  - 'SPRUCE_DOOR'
  - 'ACACIA_DOOR'
  - 'IRON_DOOR'
  - 'PISTON_MOVING_PIECE'
  - 'OAK_DOOR'
  - 'BIRCH_DOOR'
  - 'JUNGLE_DOOR'
  - 'DARK_OAK_DOOR'
  - 'BEDROCK'
  - 'WATER'
  - 'WATER_LILY'
  - 'LAVA'
  - 'STATIONARY_LAVA'
  - 'COMMAND'
  - 'BARRIER'
  - 'WOOD_PLATE'
  - 'STONE_PLATE'
  - 'GOLD_PLATE'
  - 'IRON_PLATE'
  - 'DARK_OAK_DOOR'
  - 'ACACIA_DOOR'
  - 'BIRCH_DOOR'
  - 'IRON_DOOR'
  - 'JUNGLE_DOOR'
  - 'SPRUCE_DOOR'
  - 'WOOD_DOOR'
  - 'WOODEN_DOOR'
  - 'BANNER'
  - 'WALL_BANNER'
  - 'STANDING_BANNER'
  - 'DRAGON_EGG'

only-this-blocks-will-popup-enabled: false #If this set to true, only blocks are in the list will popup
only-this-blocks-will-popup:
  - 'STONE'
  - 'GRASS'
  - 'DIRT'
  - 'COBBLESTONE'
  - 'WOOD'
  - 'SAPLING'
  - 'SAND'
  - 'GRAVEL'
  - 'GOLD_ORE'
  - 'IRON_ORE'
  - 'COAL_ORE'
  - 'LOG'
  - 'LEAVES'
  - 'SPONGE'
  - 'GLASS'
  - 'LAPIS_ORE'
  - 'LAPIS_BLOCK'
  - 'DISPENSER'
  - 'SANDSTONE'
  - 'NOTE_BLOCK'
  - 'BED_BLOCK'
  - 'POWERED_RAIL'
  - 'DETECTOR_RAIL'
  - 'WEB'
  - 'WOOL'
  - 'GOLD_BLOCK'
  - 'IRON_BLOCK'
  - 'BRICK'
  - 'TNT'
  - 'BOOKSHELF'
  - 'MOSSY_COBBLESTONE'
  - 'OBSIDIAN'
  - 'WOOD_STAIRS'
  - 'CHEST'
  - 'REDSTONE_WIRE'
  - 'DIAMOND_ORE'
  - 'DIAMOND_BLOCK'
  - 'WORKBENCH'
  - 'FURNANCE'
  - 'COBBLESTONE_STAIRS'
  - 'WOOD_PLATE'
  - 'REDSTONE_ORE'
  - 'ICE'
  - 'SNOW_BLOCK'
  - 'CACTUS'
  - 'CLAY'
  - 'JUKEBOX'
  - 'FENCE'
  - 'PUMPKIN'
  - 'NETHERRACK'
  - 'GLOWSTONE'
  - 'JACK_O_LANTERN'
  - 'CAKE_BLOCK'
  - 'STAINED_GLASS'
  - 'SMOOTH_BRICK'
  - 'IRON_FENCE'

luckychest-contents: #item:data:amount | randomly picked | add numbers ordered
  1:
    - 'GOLDEN_APPLE:0:1'
  2:
    - 'DIAMOND:0:2'

no-permission: '&cYou don''t have permission'
oneblock-exist: '&cThis is already a oneblock'
oneblock-setted: '&aYou have setted the oneblock location'
oneblock-not-exist: '&cThis is not a oneblock'
oneblock-removed: '&aYou have removed the oneblock'
oneblock-limit: '&cYou have reached the oneblocks limit'
oneblock-not-owner: '&cYou are not the owner of this oneblock'
command-help:
  - '&7'
  - '&a/oneblock add &8- &7Adds OneBlock location'
  - '&a/oneblock remove &8- &7Removes OneBlock you''re looking'